### ISSUE TITLE
“Cannot read property deserializeBinary of undefined”

### ISSUE THREAD

**Issue by domino14** [thechriswalker/twirp-js#3]
Hi, I have an error I tracked down to this module. I am using Twirp with the js generator and it seems to make a request to my Twirp server fine, but I get this error when the data comes back in protobuf format and tries to be deserialized.

**Comment by jamiehannaford** [comment]
@domino14 Did you make any progress on figuring out what went wrong? I'm also running into this with multiple `.proto` files. 

/cc @thechriswalker
